# Generated by Django 6.0.6 on 2026-07-09 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bno', models.IntegerField(primary_key=True, serialize=False)),
                ('bdate', models.DateField()),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
    ]
